services:
  service:
    build: ./
    container_name: itk
    restart: on-failure
    ports:
      - "80${SERVER_PORT}"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost${SERVER_PORT}/status"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DBNAME=${POSTGRES_DBNAME}

  db:
    image: postgres:latest
    container_name: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ./.database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DBNAME}
